/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/completeness-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_v1_admin_completeness_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_api_v1_admin_completeness_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/completeness-templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Template */
        put: operations["update_template_api_v1_admin_completeness_templates__template_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/completeness-templates/{template_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Template */
        post: operations["publish_template_api_v1_admin_completeness_templates__template_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/completeness-templates/{template_id}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy Template */
        post: operations["copy_template_api_v1_admin_completeness_templates__template_id__copy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/completeness-templates/{template_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire Template */
        post: operations["retire_template_api_v1_admin_completeness_templates__template_id__retire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application */
        get: operations["get_application_api_v1_applications__application_id__get"];
        /** Update Application */
        put: operations["update_application_api_v1_applications__application_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_applications__application_id__documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_applications__application_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_documents__document_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Document
         * @description Stream the original material to its application owner.
         */
        get: operations["download_document_api_v1_documents__document_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_v1_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/outputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Outputs */
        get: operations["list_outputs_api_v1_documents__document_id__outputs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/document-outputs/{output_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_api_v1_document_outputs__output_id__reviews_get"];
        put?: never;
        /** Create Review */
        post: operations["create_review_api_v1_document_outputs__output_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/pages/{page_number}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page Image */
        get: operations["page_image_api_v1_documents__document_id__pages__page_number__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidates */
        get: operations["list_candidates_api_v1_applications__application_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/resolutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resolutions */
        get: operations["list_resolutions_api_v1_applications__application_id__resolutions_get"];
        put?: never;
        /** Create Resolution */
        post: operations["create_resolution_api_v1_applications__application_id__resolutions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/cloud-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cloud Calls */
        get: operations["list_cloud_calls_api_v1_applications__application_id__cloud_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/completeness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Completeness */
        get: operations["get_completeness_api_v1_applications__application_id__completeness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/documents/{document_id}/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Classification */
        post: operations["confirm_classification_api_v1_applications__application_id__documents__document_id__classification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Mapping */
        post: operations["create_mapping_api_v1_applications__application_id__mappings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/mappings/{mapping_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Mapping */
        delete: operations["delete_mapping_api_v1_applications__application_id__mappings__mapping_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/waivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Waiver */
        post: operations["create_waiver_api_v1_applications__application_id__waivers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/completeness-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Completeness Runs */
        get: operations["list_completeness_runs_api_v1_applications__application_id__completeness_runs_get"];
        put?: never;
        /** Create Completeness Run */
        post: operations["create_completeness_run_api_v1_applications__application_id__completeness_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/completeness-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Completeness Run */
        get: operations["get_completeness_run_api_v1_applications__application_id__completeness_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/completeness-runs/{run_id}/printable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Printable Completeness Run */
        get: operations["printable_completeness_run_api_v1_applications__application_id__completeness_runs__run_id__printable_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationFields */
        ApplicationFields: {
            primary_borrower: components["schemas"]["PrimaryBorrower"];
            /** Product */
            product: string;
            /**
             * Application Date
             * Format: date
             */
            application_date: string;
            /** Proposed Signing Date */
            proposed_signing_date?: string | null;
        };
        /** ApplicationResponse */
        ApplicationResponse: {
            primary_borrower: components["schemas"]["PrimaryBorrower"];
            /** Product */
            product: string;
            /**
             * Application Date
             * Format: date
             */
            application_date: string;
            /** Proposed Signing Date */
            proposed_signing_date?: string | null;
            /** Id */
            id: string;
            /** Owner Id */
            owner_id: string;
            /** Lifecycle State */
            lifecycle_state: string;
            /** Version */
            version: number;
        };
        /** BlockResponse */
        BlockResponse: {
            /** Id */
            id: string;
            /** Order */
            order: number;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ] | null;
            /** Extraction Method */
            extraction_method: string;
            /** Confidence */
            confidence: number | null;
            /** Cells */
            cells: components["schemas"]["CellResponse"][];
            /** Locator */
            locator: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_upload_document_api_v1_applications__application_id__documents_post */
        Body_upload_document_api_v1_applications__application_id__documents_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CandidateResponse */
        CandidateResponse: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Output Id */
            output_id: string;
            /** Output Version */
            output_version: number;
            /** Field Key */
            field_key: string;
            /** Field Label */
            field_label: string;
            /** Group */
            group: string;
            /** Critical */
            critical: boolean;
            /** Subject Role */
            subject_role: string | null;
            /** Subject Label */
            subject_label: string | null;
            /** Raw Text */
            raw_text: string;
            /** Typed Value */
            typed_value: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence: number;
            /** Extractor */
            extractor: string;
            /** Extractor Version */
            extractor_version: string;
            /** Model Version */
            model_version: string;
            /** Prompt Version */
            prompt_version: string | null;
            /** Source Refs */
            source_refs: components["schemas"]["SourceRefResponse"][];
        };
        /** CellResponse */
        CellResponse: {
            /** Id */
            id: string;
            /** Row */
            row: number;
            /** Column */
            column: number;
            /** Text */
            text: string;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ] | null;
            /** Locator */
            locator: {
                [key: string]: unknown;
            } | null;
        };
        /** ClassificationCandidateResponse */
        ClassificationCandidateResponse: {
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /** Confidence */
            confidence: number;
            /** Method */
            method: string;
            /** Method Version */
            method_version: string;
        };
        /** CloudCallResponse */
        CloudCallResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Error Code */
            error_code: string | null;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Redaction Version */
            redaction_version: string;
            /** Source Refs */
            source_refs: {
                [key: string]: unknown;
            }[];
            /** Redacted Request */
            redacted_request: {
                [key: string]: unknown;
            };
            /** Redacted Response */
            redacted_response: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CompletenessDocumentResponse */
        CompletenessDocumentResponse: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Confirmed Category */
            confirmed_category: string | null;
            /** Classification Candidates */
            classification_candidates: components["schemas"]["ClassificationCandidateResponse"][];
            /** Seal Confirmed */
            seal_confirmed: boolean;
            /** Signature Confirmed */
            signature_confirmed: boolean;
        };
        /** CompletenessItemResponse */
        CompletenessItemResponse: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /** Order */
            order: number;
            /** Requires Seal */
            requires_seal: boolean;
            /** Requires Signature */
            requires_signature: boolean;
            /** Condition */
            condition: {
                [key: string]: unknown;
            } | null;
            /** Condition Label */
            condition_label: string | null;
            /** State */
            state: string;
            /** State Label */
            state_label: string;
            /** Evidence Document Ids */
            evidence_document_ids: string[];
            /** Reason */
            reason: string;
        };
        /** ConfirmClassificationRequest */
        ConfirmClassificationRequest: {
            category: components["schemas"]["MaterialCategory"];
        };
        /** CreateMappingRequest */
        CreateMappingRequest: {
            /** Document Id */
            document_id: string;
            /** Item Id */
            item_id: string;
        };
        /** CreateTemplateRequest */
        CreateTemplateRequest: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Product */
            product: string;
            /**
             * Borrower Type
             * @enum {string}
             */
            borrower_type: "corporate" | "individual";
            /**
             * Demo Only
             * @default false
             */
            demo_only: boolean;
            /** Items */
            items: components["schemas"]["TemplateItemInput"][];
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** CreateWaiverRequest */
        CreateWaiverRequest: {
            /** Item Id */
            item_id: string;
            /** Reason */
            reason: string;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /** Id */
            id: string;
            /** Application Id */
            application_id: string;
            /** Filename */
            filename: string;
            /** Declared Mime */
            declared_mime: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Processing Status */
            processing_status: string;
            /** Review Status */
            review_status: string;
            /** Jobs */
            jobs: components["schemas"]["JobResponse"][];
        };
        /** EvidenceReviewRequest */
        EvidenceReviewRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "seal_presence" | "signature_presence";
            /**
             * Status
             * @enum {string}
             */
            status: "present" | "absent" | "uncertain";
            /** Seal Candidate Id */
            seal_candidate_id?: string | null;
            /** Reason */
            reason: string;
        };
        /** EvidenceReviewResponse */
        EvidenceReviewResponse: {
            /** Id */
            id: string;
            /** Output Id */
            output_id: string;
            /** Seal Candidate Id */
            seal_candidate_id: string | null;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Reason */
            reason: string;
            /** Actor Id */
            actor_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobResponse */
        JobResponse: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Error Code */
            error_code: string | null;
            /** Retry Reason */
            retry_reason: string | null;
            /** Steps */
            steps: components["schemas"]["StepResponse"][];
        };
        /** LiveDraftResponse */
        LiveDraftResponse: {
            /** Template */
            template: {
                [key: string]: unknown;
            } | null;
            /** No Template Reason */
            no_template_reason: string | null;
            /** Items */
            items: components["schemas"]["CompletenessItemResponse"][];
            /** Documents */
            documents: components["schemas"]["CompletenessDocumentResponse"][];
            /** Mappings */
            mappings: components["schemas"]["MappingResponse"][];
            /** Waivers */
            waivers: components["schemas"]["WaiverResponse"][];
            /** Condition Context */
            condition_context: {
                [key: string]: boolean;
            };
            latest_run: components["schemas"]["RunSummaryResponse"] | null;
            /** Formal Run Blocked Reason */
            formal_run_blocked_reason: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** ManagedUserResponse */
        ManagedUserResponse: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Enabled */
            enabled: boolean;
            /** Version */
            version: number;
        };
        /** MappingResponse */
        MappingResponse: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Document Filename */
            document_filename: string;
            /** Item Id */
            item_id: string;
            /** Item Code */
            item_code: string;
            /** Item Label */
            item_label: string;
            /** Actor Id */
            actor_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MaterialCategory
         * @enum {string}
         */
        MaterialCategory: "basic_info" | "operation" | "loan_application" | "purpose" | "credit" | "collateral" | "other";
        /** OutputResponse */
        OutputResponse: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Format */
            format: string;
            /** Version */
            version: number;
            /** Status */
            status: string;
            /** Parser Version */
            parser_version: string;
            /** Model Version */
            model_version: string;
            /** Pages */
            pages: components["schemas"]["PageResponse"][];
        };
        /** PageResponse */
        PageResponse: {
            /** Id */
            id: string;
            /** Number */
            number: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Status */
            status: string;
            /** Error Code */
            error_code: string | null;
            /** Blocks */
            blocks: components["schemas"]["BlockResponse"][];
            /** Seals */
            seals: components["schemas"]["SealCandidateResponse"][];
        };
        /** PrimaryBorrower */
        PrimaryBorrower: {
            /**
             * Type
             * @enum {string}
             */
            type: "corporate" | "individual";
            /** Name */
            name: string;
        };
        /**
         * ProcessingStepName
         * @enum {string}
         */
        ProcessingStepName: "validation" | "parsing_ocr" | "structure_extraction" | "seal_detection" | "classification" | "candidate_extraction";
        /** ResolutionRequest */
        ResolutionRequest: {
            /**
             * Resolution Type
             * @enum {string}
             */
            resolution_type: "selected" | "corrected" | "manual";
            /** Field Key */
            field_key: string;
            subject_role?: components["schemas"]["SubjectRole"] | null;
            /** Candidate Id */
            candidate_id?: string | null;
            /**
             * Value
             * @default
             */
            value: string;
            /** Reason */
            reason?: string | null;
        };
        /** ResolutionResponse */
        ResolutionResponse: {
            /** Id */
            id: string;
            /** Application Id */
            application_id: string;
            /** Candidate Id */
            candidate_id: string | null;
            /** Field Key */
            field_key: string;
            /** Field Label */
            field_label: string;
            /** Subject Role */
            subject_role: string | null;
            /** Resolution Type */
            resolution_type: string;
            /** Typed Value */
            typed_value: {
                [key: string]: unknown;
            };
            /** No Material Source */
            no_material_source: boolean;
            /** Reason */
            reason: string | null;
            /** Actor Id */
            actor_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RetryRequest */
        RetryRequest: {
            /** Reason */
            reason: string;
            /** Selected Steps */
            selected_steps: components["schemas"]["ProcessingStepName"][];
        };
        /** RunDetailResponse */
        RunDetailResponse: {
            /** Id */
            id: string;
            /** Application Id */
            application_id: string;
            /** Template Snapshot */
            template_snapshot: {
                [key: string]: unknown;
            };
            /** Input Snapshot */
            input_snapshot: {
                [key: string]: unknown;
            };
            /** Result Snapshot */
            result_snapshot: {
                [key: string]: unknown;
            };
            /** Content Hash */
            content_hash: string;
            /** Status */
            status: string;
            /** Stale */
            stale: boolean;
            /** Stale Reason */
            stale_reason: string | null;
            /** Actor Id */
            actor_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RunSummaryResponse */
        RunSummaryResponse: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Status */
            status: string;
            /** Stale */
            stale: boolean;
            /** Stale Reason */
            stale_reason: string | null;
            /** Content Hash */
            content_hash: string;
            /** Template Code */
            template_code: string;
            /** Template Version */
            template_version: number;
            /** Actor Id */
            actor_id: string;
        };
        /** SealCandidateResponse */
        SealCandidateResponse: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Confidence */
            confidence: number;
            /** Model Version */
            model_version: string;
        };
        /** SourceRefResponse */
        SourceRefResponse: {
            /** Document Id */
            document_id: string;
            /** Output Id */
            output_id: string;
            /** Output Version */
            output_version: number;
            /** Page Number */
            page_number: number | null;
            /** Block Id */
            block_id: string;
            /** Block Order */
            block_order: number;
            /** Cell Id */
            cell_id?: string | null;
            /** Locator */
            locator?: {
                [key: string]: unknown;
            } | null;
            /** Bbox */
            bbox?: unknown[] | null;
            /** Cell Locator */
            cell_locator?: {
                [key: string]: unknown;
            } | null;
            /** Cell Bbox */
            cell_bbox?: unknown[] | null;
        };
        /** StepResponse */
        StepResponse: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Error Code */
            error_code: string | null;
        };
        /**
         * SubjectRole
         * @enum {string}
         */
        SubjectRole: "primary_borrower" | "legal_representative" | "shareholder" | "spouse" | "guarantor" | "collateral_owner";
        /** TemplateItemInput */
        TemplateItemInput: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            category: components["schemas"]["MaterialCategory"];
            /**
             * Requires Seal
             * @default false
             */
            requires_seal: boolean;
            /**
             * Requires Signature
             * @default false
             */
            requires_signature: boolean;
            /** Condition */
            condition?: {
                [key: string]: unknown;
            } | null;
        };
        /** TemplateItemResponse */
        TemplateItemResponse: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /** Order */
            order: number;
            /** Requires Seal */
            requires_seal: boolean;
            /** Requires Signature */
            requires_signature: boolean;
            /** Condition */
            condition: {
                [key: string]: unknown;
            } | null;
        };
        /** TemplateResponse */
        TemplateResponse: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Product */
            product: string;
            /** Borrower Type */
            borrower_type: string;
            /** Version */
            version: number;
            /** Status */
            status: string;
            /** Demo Only */
            demo_only: boolean;
            /** Content Hash */
            content_hash: string;
            /** Published At */
            published_at: string | null;
            /** Retired At */
            retired_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Items */
            items: components["schemas"]["TemplateItemResponse"][];
        };
        /** UpdateApplicationRequest */
        UpdateApplicationRequest: {
            primary_borrower: components["schemas"]["PrimaryBorrower"];
            /** Product */
            product: string;
            /**
             * Application Date
             * Format: date
             */
            application_date: string;
            /** Proposed Signing Date */
            proposed_signing_date?: string | null;
            /** Version */
            version: number;
        };
        /**
         * UpdateTemplateRequest
         * @description Draft-only edit; published/retired versions stay immutable.
         */
        UpdateTemplateRequest: {
            /** Name */
            name: string;
            /** Items */
            items: components["schemas"]["TemplateItemInput"][];
        };
        /** UpdateUserRequest */
        UpdateUserRequest: {
            /** Enabled */
            enabled: boolean;
            /** Version */
            version: number;
        };
        /** UploadResponse */
        UploadResponse: {
            document: components["schemas"]["DocumentResponse"];
            job: components["schemas"]["JobResponse"];
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WaiverResponse */
        WaiverResponse: {
            /** Id */
            id: string;
            /** Item Id */
            item_id: string;
            /** Item Code */
            item_code: string;
            /** Item Label */
            item_label: string;
            /** Reason */
            reason: string;
            /** Actor Id */
            actor_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedUserResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_admin_completeness_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_v1_admin_completeness_templates_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_v1_admin_completeness_templates__template_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_template_api_v1_admin_completeness_templates__template_id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copy_template_api_v1_admin_completeness_templates__template_id__copy_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_template_api_v1_admin_completeness_templates__template_id__retire_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationFields"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_api_v1_applications__application_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_applications__application_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_applications__application_id__documents_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_applications__application_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_documents__document_id__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_document_api_v1_documents__document_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_v1_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_outputs_api_v1_documents__document_id__outputs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_api_v1_document_outputs__output_id__reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                output_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceReviewResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_api_v1_document_outputs__output_id__reviews_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                output_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_image_api_v1_documents__document_id__pages__page_number__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                page_number: number;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_api_v1_applications__application_id__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resolutions_api_v1_applications__application_id__resolutions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolutionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_resolution_api_v1_applications__application_id__resolutions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cloud_calls_api_v1_applications__application_id__cloud_calls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudCallResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_completeness_api_v1_applications__application_id__completeness_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_classification_api_v1_applications__application_id__documents__document_id__classification_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                application_id: string;
                document_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmClassificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletenessDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mapping_api_v1_applications__application_id__mappings_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMappingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_mapping_api_v1_applications__application_id__mappings__mapping_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                application_id: string;
                mapping_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_waiver_api_v1_applications__application_id__waivers_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWaiverRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaiverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_completeness_runs_api_v1_applications__application_id__completeness_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_completeness_run_api_v1_applications__application_id__completeness_runs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
                icrm_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_completeness_run_api_v1_applications__application_id__completeness_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                run_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    printable_completeness_run_api_v1_applications__application_id__completeness_runs__run_id__printable_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                run_id: string;
            };
            cookie?: {
                icrm_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
